- name: monitor
  hosts: all
  become: yes
  remote_user: admin

  handlers:
  - name: prometheus_restart_service
    service: 
      name: prometheus
      state: restarted
  - name: grafana_restart_service
    service: 
      name: grafana-server
      state: restarted

  tasks:
  - name: prometheus - add target with ec2_sd
    blockinfile:
      path: /etc/prometheus/prometheus.yml
      insertafter: "^scrape_configs:"
      block: |
          - job_name: 'aws'
            ec2_sd_configs:
              - region: 'eu-west-1'
                access_key: '${aws_access_key}'
                secret_key: '${aws_secret_key}'
                port: 2379
                filters:
                  - name: tag:Cluster
                    values:
                      - ${etcd_cluster}
    notify:
    - prometheus_restart_service
 # Not working yet
  # - name: grafana - create prometheus datasource
  #   grafana_datasource:
  #     grafana_url: "http://localhost:3000/"
  #     name: "prometheus"
  #     org_id: "1"
  #     ds_type: "prometheus"
  #     url: "http://localhost:9090"

 
  # - name: grafana - Import dashboard etcd
  #   grafana_dashboard:
  #     grafana_url: "http://localhost:3000/"
  #     state: present
  #     message: Updated by ansible
  #     overwrite: yes
  #     path: /tmp/etcd.json
  #   notify:
  #   - grafana_restart_service


    
